### ISSUE TITLE
Не удалось настроить: ImportError: Using http2=True, but the 'h2' package is not installed. Make sure to install httpx using `pip install httpx[http2]`.

### ISSUE THREAD

**Issue by sisoftrg** [dmamontov/hass-tattelecom-intercom#1]
Инеграция успешно устанавливается, авторизуется по SMS при добавлении, затем переходит в состояние "Не удалось настроить".

В логах ошибка:
```
Logger: homeassistant.config_entries
Source: helpers/httpx_client.py:66
First occurred: 22:01:31 (1 occurrences)
Last logged: 22:01:31

Error setting up entry 79xxxxxxxxx for tattelecom_intercom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tattelecom_intercom/__init__.py", line 48, in async_setup_entry
    _updater: IntercomUpdater = IntercomUpdater(
  File "/config/custom_components/tattelecom_intercom/updater.py", line 96, in __init__
    create_async_httpx_client(
  File "/usr/src/homeassistant/homeassistant/helpers/httpx_client.py", line 66, in create_async_httpx_client
    client = HassHttpXAsyncClient(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1386, in __init__
    raise ImportError(
ImportError: Using http2=True, but the 'h2' package is not installed. Make sure to install httpx using `pip install httpx[http2]`.
```

Пробовал удалить и установить HACS, этот компонент - видно, что не хватает зависимости, но ошибка не решается. как доустановить пакет не понятно - стандартно установлены HassOS 9.0, Homeassistant 2022.9.7, Supervisor 2022.09.1, HACS 1.27.2 (последние доступные версии всего). другие интеграции из HACS работают.

**Comment by dmamontov** [comment]
Данную проблему уже решали в телеграм. 

shell_command:
  install_httpx: pip install httpx[http2]

script:
install_httpx:
  alias: Install httpx
  sequence:
    - service: shell_command.install_httpx

Как я понимаю так решается проблема с любыми зависимостями

И без этого пакета, запросы к апи просто попадут в бан через определенное время

**Comment by sisoftrg** [comment]
Благодарю, добавление скрипта и его выполнение решило проблему, картинка есть.
