### ISSUE TITLE
Please report issue to the custom integration author for tattelecom_intercom

### ISSUE THREAD

**Issue by panfmik** [dmamontov/hass-tattelecom-intercom#3]
**Describe the bug**
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for tattelecom_intercom using this method at custom_components/tattelecom_intercom/__init__.py, line 75: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Please complete the following information:**
 - HASS version: [2023.2.2]
 - Component version [1.1.0]

**Comment by panfmik** [comment]
https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/

**Comment by dmamontov** [comment]
@panfmik fixed in version https://github.com/dmamontov/hass-tattelecom-intercom/releases/tag/v2.0.0

thanks
